### ISSUE TITLE
Question about react streaming

### ISSUE THREAD

**Issue by boga001** [batijs/bati#283]
I created a new vite react using Bati with express, tailwind, vite and react.

When I serve the dev or preview I get this message in console about userAgent:
```
[react-streaming@0.3.28][Warning] HTML streaming (https://vike.dev/streaming) disabled because User Agent is unknown: make sure to provide pageContext.userAgent (typically with renderPage({ userAgent: req.headers['user-agent'] }), see https://vike.dev/renderPage) (so that HTML streaming can be disabled for bots such as Google Bot).
```

When I add userAgent in `vike-handler.ts`:
```
const pageContextInit = { ...context, urlOriginal: request.url, userAgent: request.headers.get('user-agent') };
  const pageContext = await renderPage(pageContextInit);
```

I get the error message:
```
Error: [react-streaming@0.3.28][Wrong Usage] Cannot inject following chunk after stream has ended:
```

What would be the correct way to do this? This is a default fresh install with Bati so maybe this can be improved?

Thanks

**Comment by magne4000** [comment]
I quickly tried with `pnpm create @batijs/app --react --express --tailwind` and do not have the issue, can you provide a reproduction repository?
Also, which browser, node version, and package manager are you using?

**Comment by magne4000** [comment]
Nevermind, I managed to get the warning, I'm checking it :+1:

**Comment by magne4000** [comment]
@brillout I might need your help on this one

**Comment by brillout** [comment]
Is it reproducible without the universal handler part? I can have a look at a reproduction.

**Comment by magne4000** [comment]
> Is it reproducible without the universal handler part? I can have a look at a reproduction.

@brillout It probably works when not using the universal handler (i.e. with node Stream).

I managed to reproduce the issue with Universal Handler with any Server. To reproduce `pnpm create @batijs/app --react --hono --tailwind` or `pnpm create @batijs/app --react --express --tailwind`, then edit `server/vike-handler.ts` to add `headersOriginal: request.headers` to `pageContextInit`. Then `pnpm run dev` and navigate to any page to trigger the issue.

The issue seems to come from [react-streaming/src/server/renderToStream/createReadableWrapper.ts](https://github.com/brillout/react-streaming/blob/61e57b22b8f7d0f3d1d3f0abb903b6d6e266b8fb/src/server/renderToStream/createReadableWrapper.ts#L56) being called too soon (for instance, if I just manually set timeout to 1000 it "works" in this particular scenario). I'm not familiar with how `react-streaming` yet, but I can take a look.

So this seems related to `ReadableStream` only, but I have the feeling that anytime we're using `ReadableStream`, we might potentially have this issue currently.

**Comment by brillout** [comment]
> but I can take a look.

:+1: That'd be great. But let me know how it goes, I can have a look at it as well.

**Comment by magne4000** [comment]
@brillout I think I have a proper fix https://github.com/vikejs/vike/pull/1718

**Comment by magne4000** [comment]
In the mean time, I disabled `stream` by default as it was before.

**Comment by boga001** [comment]
Thanks guys! 🥳

**Comment by brillout** [comment]
We refactored a couple of things. The handling of the React stream and its edge cases is now more robust, but let me know if you run into any issue (it's possible that I may have introduced a minor regression in and there).

Btw. in case your company is up for it, [we're looking for sponsors](https://github.com/vikejs/vike/issues/1350) which makes a massive difference to the project.
